export const fakeAddresses: { line1: string; line2: string }[] = [
  { line1: "Jalan Medokan Ayu No. 86, Ville", line2: "KOTA LANGSA, KEPULAUAN RIAU, ID, 74087" },
  { line1: "Jalan HOS. Cokroaminoto No. 4, Ville", line2: "KOTA MATARAM, KALIMANTAN BARAT, ID, 85522" },
  { line1: "Gg. Jamika No. 10, Ville", line2: "KOTA PANGKALPINANG, BANTEN, ID, 25880" },
  { line1: "Gang Kutai No. 80, Ville", line2: "KOTA BEKASI, SULAWESI TENGAH, ID, 44153" },
  { line1: "Jl. Kiaracondong No. 00, Ville", line2: "KOTA DEPOK, RIAU, ID, 46741" },
  { line1: "Gg. Wonoayu No. 48, Ville", line2: "KOTA BATU, JAWA TIMUR, ID, 19658" },
  { line1: "Jl. Wonoayu No. 5, Ville", line2: "KOTA BANJAR, KALIMANTAN BARAT, ID, 58231" },
  { line1: "Jl. Dipatiukur No. 51, Ville", line2: "KOTA AMBON, DI YOGYAKARTA, ID, 84448" },
  { line1: "Gg. Antapani Lama No. 75, Ville", line2: "KOTA TEGAL, KALIMANTAN TENGAH, ID, 88965" },
  { line1: "Gang Ir. H. Djuanda No. 952, Ville", line2: "KOTA SORONG, PAPUA, ID, 87493" },
  { line1: "Jl. M.H Thamrin No. 7, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA BARAT, RIAU, ID, 29130" },
  { line1: "Jl. Laswi No. 47, Ville", line2: "KOTA PARIAMAN, KEPULAUAN BANGKA BELITUNG, ID, 99702" },
  { line1: "Gg. Asia Afrika No. 02, Ville", line2: "KOTA BINJAI, JAWA BARAT, ID, 55118" },
  { line1: "Jl. Gardujati No. 37, Ville", line2: "KOTA DUMAI, KALIMANTAN BARAT, ID, 04678" },
  { line1: "Gg. Kiaracondong No. 925, Ville", line2: "KOTA SIBOLGA, KALIMANTAN SELATAN, ID, 19266" },
  { line1: "Gang Suniaraja No. 0, Ville", line2: "KOTA PALU, SULAWESI TENGAH, ID, 07405" },
  { line1: "Jalan Medokan Ayu No. 60, Ville", line2: "KOTA SURABAYA, SULAWESI TENGAH, ID, 42090" },
  { line1: "Gg. Kapten Muslihat No. 791, Ville", line2: "KOTA SERANG, ACEH, ID, 16365" },
  { line1: "Gang Cihampelas No. 7, Ville", line2: "KOTA MANADO, DKI JAKARTA, ID, 45184" },
  { line1: "Gg. Cikutra Barat No. 03, Ville", line2: "KOTA KOTAMOBAGU, SULAWESI TENGAH, ID, 35152" },
  { line1: "Gang Kendalsari No. 9, Ville", line2: "KOTA CILEGON, RIAU, ID, 01050" },
  { line1: "Jl. KH Amin Jasuta No. 199, Ville", line2: "KOTA PALEMBANG, RIAU, ID, 23609" },
  { line1: "Jl. Rajawali Barat No. 15, Ville", line2: "KOTA DUMAI, JAWA BARAT, ID, 53480" },
  { line1: "Gang Raya Setiabudhi No. 8, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA UTARA, MALUKU UTARA, ID, 77508" },
  { line1: "Gang Jakarta No. 8, Ville", line2: "KOTA TARAKAN, SULAWESI UTARA, ID, 64880" },
  { line1: "Jalan Veteran No. 6, Ville", line2: "KOTA LUBUKLINGGAU, KEPULAUAN RIAU, ID, 73189" },
  { line1: "Gg. Indragiri No. 721, Ville", line2: "KOTA SURAKARTA, PAPUA, ID, 78732" },
  { line1: "Gg. Jend. A. Yani No. 9, Ville", line2: "KOTA YOGYAKARTA, LAMPUNG, ID, 83961" },
  { line1: "Gang W.R. Supratman No. 656, Ville", line2: "KOTA MALANG, SUMATERA BARAT, ID, 13320" },
  { line1: "Jl. Kebonjati No. 0, Ville", line2: "KOTA PONTIANAK, KEPULAUAN BANGKA BELITUNG, ID, 77768" },
  { line1: "Gang Setiabudhi No. 42, Ville", line2: "KOTA PAREPARE, BANTEN, ID, 75645" },
  { line1: "Jl. W.R. Supratman No. 3, Ville", line2: "KOTA SUKABUMI, DKI JAKARTA, ID, 79066" },
  { line1: "Gang Rajiman No. 98, Ville", line2: "KOTA SURABAYA, DI YOGYAKARTA, ID, 68544" },
  { line1: "Jl. Ronggowarsito No. 8, Ville", line2: "KOTA CIREBON, JAWA TIMUR, ID, 72141" },
  { line1: "Jalan Asia Afrika No. 8, Ville", line2: "KOTA KEDIRI, SUMATERA BARAT, ID, 23881" },
  { line1: "Jalan W.R. Supratman No. 817, Ville", line2: "KOTA MAKASSAR, DKI JAKARTA, ID, 06830" },
  { line1: "Jl. Jend. Sudirman No. 17, Ville", line2: "KOTA BEKASI, KEPULAUAN BANGKA BELITUNG, ID, 96249" },
  { line1: "Jalan Wonoayu No. 48, Ville", line2: "KOTA MALANG, MALUKU UTARA, ID, 25774" },
  { line1: "Jl. Kebonjati No. 7, Ville", line2: "KOTA SERANG, KALIMANTAN BARAT, ID, 33060" },
  { line1: "Jalan Ciumbuleuit No. 733, Ville", line2: "KOTA GORONTALO, SULAWESI TENGAH, ID, 29889" },
  { line1: "Jalan Moch. Ramdan No. 430, Ville", line2: "KOTA MAKASSAR, JAWA TENGAH, ID, 87477" },
  { line1: "Jalan Ahmad Dahlan No. 92, Ville", line2: "KOTA MANADO, SULAWESI TENGGARA, ID, 46574" },
  { line1: "Jalan Siliwangi No. 046, Ville", line2: "KOTA PEKALONGAN, SULAWESI TENGGARA, ID, 46220" },
  { line1: "Gg. K.H. Wahid Hasyim No. 2, Ville", line2: "KOTA MADIUN, DKI JAKARTA, ID, 45862" },
  { line1: "Gg. Kebonjati No. 338, Ville", line2: "KOTA BOGOR, SULAWESI UTARA, ID, 89722" },
  { line1: "Gang H.J Maemunah No. 4, Ville", line2: "KOTA TERNATE, SULAWESI UTARA, ID, 58716" },
  { line1: "Jalan Cikutra Barat No. 2, Ville", line2: "KOTA DENPASAR, KEPULAUAN BANGKA BELITUNG, ID, 65090" },
  { line1: "Gang Jakarta No. 63, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA UTARA, NUSA TENGGARA BARAT, ID, 49212" },
  { line1: "Gg. Pasteur No. 735, Ville", line2: "KOTA SORONG, RIAU, ID, 01865" },
  { line1: "Jalan Erlangga No. 0, Ville", line2: "KOTA BUKITTINGGI, KALIMANTAN SELATAN, ID, 60395" },
  { line1: "Jl. Ahmad Dahlan No. 356, Ville", line2: "KOTA DENPASAR, KALIMANTAN SELATAN, ID, 39317" },
  { line1: "Jalan Asia Afrika No. 196, Ville", line2: "KOTA LUBUKLINGGAU, BANTEN, ID, 67893" },
  { line1: "Gg. Yos Sudarso No. 796, Ville", line2: "KOTA BOGOR, SULAWESI UTARA, ID, 61850" },
  { line1: "Jl. Rajawali Barat No. 44, Ville", line2: "KOTA PASURUAN, SULAWESI BARAT, ID, 30201" },
  { line1: "Jalan M.T Haryono No. 331, Ville", line2: "KOTA PEKANBARU, SUMATERA BARAT, ID, 01074" },
  { line1: "Gg. Medokan Ayu No. 85, Ville", line2: "KOTA SIBOLGA, PAPUA, ID, 74339" },
  { line1: "Gg. Waringin No. 0, Ville", line2: "KOTA BANDAR LAMPUNG, SULAWESI TENGGARA, ID, 81292" },
  { line1: "Jalan Cihampelas No. 991, Ville", line2: "KOTA PEKANBARU, SUMATERA UTARA, ID, 49913" },
  { line1: "Gang Kebonjati No. 22, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA BARAT, MALUKU UTARA, ID, 46859" },
  { line1: "Jalan Peta No. 64, Ville", line2: "KOTA PAYAKUMBUH, JAWA TENGAH, ID, 58126" },
  { line1: "Jl. Pasir Koja No. 8, Ville", line2: "KOTA SABANG, SUMATERA SELATAN, ID, 11673" },
  { line1: "Gg. Stasiun Wonokromo No. 52, Ville", line2: "KOTA PRABUMULIH, SUMATERA UTARA, ID, 36715" },
  { line1: "Gg. R.E Martadinata No. 0, Ville", line2: "KOTA PADANG SIDEMPUAN, JAWA BARAT, ID, 09920" },
  { line1: "Gg. Moch. Ramdan No. 33, Ville", line2: "KOTA PEMATANGSIANTAR, PAPUA, ID, 12400" },
  { line1: "Jl. Gedebage Selatan No. 6, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA TIMUR, SULAWESI UTARA, ID, 87032" },
  { line1: "Gang Rajawali Barat No. 03, Ville", line2: "KOTA MATARAM, DKI JAKARTA, ID, 78640" },
  { line1: "Gang Dipatiukur No. 7, Ville", line2: "KOTA BANDA ACEH, DI YOGYAKARTA, ID, 09578" },
  { line1: "Gg. Sentot Alibasa No. 162, Ville", line2: "KOTA TERNATE, PAPUA BARAT, ID, 87294" },
  { line1: "Gg. Sukajadi No. 7, Ville", line2: "KOTA LUBUKLINGGAU, SULAWESI TENGGARA, ID, 39837" },
  { line1: "Gang Kendalsari No. 138, Ville", line2: "KOTA DEPOK, KALIMANTAN UTARA, ID, 63414" },
  { line1: "Jalan Lembong No. 86, Ville", line2: "KOTA LUBUKLINGGAU, MALUKU, ID, 91914" },
  { line1: "Jl. Abdul Muis No. 08, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA PUSAT, PAPUA, ID, 81888" },
  { line1: "Jl. Pelajar Pejuang No. 02, Ville", line2: "KOTA PEKANBARU, NUSA TENGGARA BARAT, ID, 44762" },
  { line1: "Jl. Rajiman No. 1, Ville", line2: "KOTA BITUNG, KEPULAUAN BANGKA BELITUNG, ID, 24669" },
  { line1: "Gg. Merdeka No. 856, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA BARAT, SULAWESI SELATAN, ID, 46611" },
  { line1: "Gang Rajiman No. 27, Ville", line2: "KOTA SAWAHLUNTO, KALIMANTAN SELATAN, ID, 44188" },
  { line1: "Gg. Moch. Toha No. 9, Ville", line2: "KOTA SAWAHLUNTO, KALIMANTAN BARAT, ID, 99504" },
  { line1: "Jl. Cikutra Timur No. 2, Ville", line2: "KOTA MANADO, SULAWESI BARAT, ID, 26205" },
  { line1: "Jalan H.J Maemunah No. 2, Ville", line2: "KOTA DUMAI, SULAWESI SELATAN, ID, 44540" },
  { line1: "Jl. Sukajadi No. 4, Ville", line2: "KOTA PALANGKARAYA, PAPUA, ID, 54773" },
  { line1: "Gang Stasiun Wonokromo No. 16, Ville", line2: "KOTA PARIAMAN, JAWA TIMUR, ID, 69364" },
  { line1: "Jl. Ahmad Dahlan No. 24, Ville", line2: "KOTA JAYAPURA, PAPUA BARAT, ID, 18432" },
  { line1: "Jalan Monginsidi No. 38, Ville", line2: "KOTA TARAKAN, PAPUA, ID, 72739" },
  { line1: "Jl. Raya Setiabudhi No. 1, Ville", line2: "KOTA TANJUNGPINANG, LAMPUNG, ID, 84557" },
  { line1: "Jalan Ciwastra No. 23, Ville", line2: "KOTA TANJUNGBALAI, DI YOGYAKARTA, ID, 53055" },
  { line1: "Jalan Jend. Sudirman No. 30, Ville", line2: "KOTA TUAL, ACEH, ID, 22534" },
  { line1: "Jalan Jend. Sudirman No. 38, Ville", line2: "KOTA PADANGPANJANG, MALUKU UTARA, ID, 90680" },
  { line1: "Jalan Kutisari Selatan No. 216, Ville", line2: "KOTA BIMA, NUSA TENGGARA BARAT, ID, 93046" },
  { line1: "Gang Jend. A. Yani No. 320, Ville", line2: "KOTA KEDIRI, SUMATERA SELATAN, ID, 73432" },
  { line1: "Jl. Dr. Djunjunan No. 4, Ville", line2: "KOTA TANJUNGPINANG, NUSA TENGGARA TIMUR, ID, 54486" },
  { line1: "Jl. M.T Haryono No. 34, Ville", line2: "KOTA SORONG, SUMATERA BARAT, ID, 30437" },
  { line1: "Jl. Ahmad Dahlan No. 217, Ville", line2: "KOTA MOJOKERTO, JAWA BARAT, ID, 54976" },
  { line1: "Gang Cihampelas No. 17, Ville", line2: "KOTA CIMAHI, JAWA BARAT, ID, 29551" },
  { line1: "Gg. Sentot Alibasa No. 3, Ville", line2: "KOTA BALIKPAPAN, SULAWESI UTARA, ID, 49078" },
  { line1: "Gg. Bangka Raya No. 004, Ville", line2: "KOTA YOGYAKARTA, SUMATERA UTARA, ID, 16371" },
  { line1: "Jalan Joyoboyo No. 225, Ville", line2: "KOTA PEKALONGAN, JAMBI, ID, 20456" },
  { line1: "Gg. Rajiman No. 668, Ville", line2: "KOTA MAGELANG, SULAWESI TENGAH, ID, 21629" },
  { line1: "Jalan Ronggowarsito No. 4, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA SELATAN, RIAU, ID, 40643" },
  { line1: "Jl. Yos Sudarso No. 509, Ville", line2: "KOTA MAGELANG, KALIMANTAN TIMUR, ID, 40257" },
  { line1: "Jl. Raya Ujungberung No. 4, Ville", line2: "KOTA PURWOKERTO, NUSA TENGGARA BARAT, ID, 61601" },
  { line1: "Gang Suniaraja No. 745, Ville", line2: "KOTA PALOPO, GORONTALO, ID, 22152" },
  { line1: "Jalan K.H. Wahid Hasyim No. 2, Ville", line2: "KOTA MAKASSAR, SULAWESI UTARA, ID, 19828" },
  { line1: "Gg. Astana Anyar No. 83, Ville", line2: "KOTA BIMA, BALI, ID, 03655" },
  { line1: "Jalan Cikutra Timur No. 8, Ville", line2: "KOTA BUKITTINGGI, MALUKU, ID, 48607" },
  { line1: "Gg. Otto Iskandardinata No. 17, Ville", line2: "KOTA SORONG, MALUKU UTARA, ID, 57662" },
  { line1: "Gg. Kebonjati No. 547, Ville", line2: "KOTA KOTAMOBAGU, LAMPUNG, ID, 64759" },
  { line1: "Gang KH Amin Jasuta No. 3, Ville", line2: "KOTA SURAKARTA, BENGKULU, ID, 02672" },
  { line1: "Gg. Kutai No. 6, Ville", line2: "KOTA DEPOK, SUMATERA SELATAN, ID, 59741" },
  { line1: "Gang Raya Ujungberung No. 1, Ville", line2: "KOTA LHOKSEUMAWE, MALUKU UTARA, ID, 00558" },
  { line1: "Gg. M.T Haryono No. 904, Ville", line2: "KOTA LANGSA, SULAWESI TENGAH, ID, 76965" },
  { line1: "Gang Gardujati No. 6, Ville", line2: "KOTA SAMARINDA, MALUKU, ID, 53107" },
  { line1: "Jalan Rumah Sakit No. 302, Ville", line2: "KOTA CIMAHI, BENGKULU, ID, 59145" },
  { line1: "Jl. Abdul Muis No. 57, Ville", line2: "KOTA SURABAYA, DKI JAKARTA, ID, 94914" },
  { line1: "Jalan Rawamangun No. 8, Ville", line2: "KOTA PRABUMULIH, KALIMANTAN TENGAH, ID, 10602" },
  { line1: "Jalan Suniaraja No. 97, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA PUSAT, LAMPUNG, ID, 63402" },
  { line1: "Gg. Waringin No. 843, Ville", line2: "KOTA MATARAM, KALIMANTAN SELATAN, ID, 56506" },
  { line1: "Gang Kutisari Selatan No. 3, Ville", line2: "KOTA PADANG, KEPULAUAN RIAU, ID, 89484" },
  { line1: "Jalan Gardujati No. 69, Ville", line2: "KOTA MEULABOH, LAMPUNG, ID, 49414" },
  { line1: "Jl. Cikapayang No. 942, Ville", line2: "KOTA TERNATE, GORONTALO, ID, 71868" },
  { line1: "Jl. S. Parman No. 7, Ville", line2: "KOTA PANGKALPINANG, KALIMANTAN TENGAH, ID, 65735" },
  { line1: "Gang Gardujati No. 34, Ville", line2: "KOTA SUBULUSSALAM, KALIMANTAN TIMUR, ID, 69532" },
  { line1: "Gg. Tubagus Ismail No. 560, Ville", line2: "KOTA MADIUN, JAWA BARAT, ID, 30899" },
  { line1: "Gg. Raya Setiabudhi No. 793, Ville", line2: "KOTA KEDIRI, SUMATERA BARAT, ID, 96608" },
  { line1: "Jalan Jend. A. Yani No. 1, Ville", line2: "KOTA PALU, RIAU, ID, 91487" },
  { line1: "Gang Sukajadi No. 4, Ville", line2: "KOTA TANJUNGBALAI, NUSA TENGGARA BARAT, ID, 05215" },
  { line1: "Gang Rajawali Timur No. 808, Ville", line2: "KOTA CIMAHI, SULAWESI TENGAH, ID, 28432" },
  { line1: "Gang S. Parman No. 2, Ville", line2: "KOTA SUKABUMI, MALUKU UTARA, ID, 09337" },
  { line1: "Jl. Bangka Raya No. 094, Ville", line2: "KOTA DENPASAR, SULAWESI UTARA, ID, 99524" },
  { line1: "Gang Pacuan Kuda No. 12, Ville", line2: "KOTA KEDIRI, KALIMANTAN UTARA, ID, 56577" },
  { line1: "Gg. K.H. Wahid Hasyim No. 140, Ville", line2: "KOTA BANJARMASIN, KALIMANTAN TENGAH, ID, 91788" },
  { line1: "Gg. Otto Iskandardinata No. 61, Ville", line2: "KOTA SUKABUMI, NUSA TENGGARA TIMUR, ID, 84439" },
  { line1: "Jalan Cihampelas No. 364, Ville", line2: "KOTA BANJARBARU, SULAWESI BARAT, ID, 86792" },
  { line1: "Jalan Joyoboyo No. 128, Ville", line2: "KOTA SUNGAI PENUH, PAPUA BARAT, ID, 20802" },
  { line1: "Gg. Medokan Ayu No. 6, Ville", line2: "KOTA TANGERANG SELATAN, KALIMANTAN UTARA, ID, 30703" },
  { line1: "Gang Pasteur No. 480, Ville", line2: "KOTA BANDAR LAMPUNG, NUSA TENGGARA TIMUR, ID, 64038" },
  { line1: "Gang Yos Sudarso No. 11, Ville", line2: "KOTA SAWAHLUNTO, BENGKULU, ID, 83976" },
  { line1: "Jl. Ciwastra No. 518, Ville", line2: "KOTA PAGARALAM, SULAWESI SELATAN, ID, 15672" },
  { line1: "Gg. M.T Haryono No. 628, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA SELATAN, KALIMANTAN BARAT, ID, 89369" },
  { line1: "Jalan K.H. Wahid Hasyim No. 55, Ville", line2: "KOTA BINJAI, KALIMANTAN UTARA, ID, 76782" },
  { line1: "Gang Merdeka No. 269, Ville", line2: "KOTA KEDIRI, SULAWESI SELATAN, ID, 22663" },
  { line1: "Jalan Otto Iskandardinata No. 673, Ville", line2: "KOTA PURWOKERTO, DKI JAKARTA, ID, 37751" },
  { line1: "Jl. Kutisari Selatan No. 774, Ville", line2: "KOTA TEGAL, LAMPUNG, ID, 89263" },
  { line1: "Gang Gedebage Selatan No. 073, Ville", line2: "KOTA SUKABUMI, BALI, ID, 69797" },
  { line1: "Gang Laswi No. 954, Ville", line2: "KOTA KOTAMOBAGU, BANTEN, ID, 83339" },
  { line1: "Gang M.H Thamrin No. 557, Ville", line2: "KOTA SAMARINDA, MALUKU, ID, 63591" },
  { line1: "Gg. Merdeka No. 975, Ville", line2: "KOTA PALOPO, KALIMANTAN TIMUR, ID, 93507" },
  { line1: "Jl. Wonoayu No. 532, Ville", line2: "KOTA TIDORE KEPULAUAN, SUMATERA SELATAN, ID, 81358" },
  { line1: "Jalan Rumah Sakit No. 92, Ville", line2: "KOTA MAGELANG, GORONTALO, ID, 00727" },
  { line1: "Jalan Ahmad Yani No. 4, Ville", line2: "KOTA PAREPARE, JAMBI, ID, 28442" },
  { line1: "Gg. K.H. Wahid Hasyim No. 83, Ville", line2: "KOTA TARAKAN, PAPUA, ID, 92884" },
  { line1: "Jalan Pelajar Pejuang No. 5, Ville", line2: "KOTA PEMATANGSIANTAR, SULAWESI SELATAN, ID, 25575" },
  { line1: "Jl. Cempaka No. 1, Ville", line2: "KOTA TEBINGTINGGI, SULAWESI TENGAH, ID, 57522" },
  { line1: "Gg. Jakarta No. 2, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA TIMUR, NUSA TENGGARA BARAT, ID, 44190" },
  { line1: "Jl. Jend. Sudirman No. 8, Ville", line2: "KOTA BANDA ACEH, PAPUA, ID, 87792" },
  { line1: "Gg. Moch. Toha No. 48, Ville", line2: "KOTA AMBON, SUMATERA BARAT, ID, 22080" },
  { line1: "Jalan Jayawijaya No. 91, Ville", line2: "KOTA SAWAHLUNTO, BENGKULU, ID, 44236" },
  { line1: "Gang Jamika No. 2, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA UTARA, GORONTALO, ID, 90278" },
  { line1: "Jl. Rajiman No. 05, Ville", line2: "KOTA BINJAI, KALIMANTAN TENGAH, ID, 47066" },
  { line1: "Jalan Asia Afrika No. 787, Ville", line2: "KOTA PALOPO, JAWA TIMUR, ID, 85980" },
  { line1: "Gang M.T Haryono No. 6, Ville", line2: "KOTA PAYAKUMBUH, JAWA TENGAH, ID, 13725" },
  { line1: "Jalan Pasteur No. 6, Ville", line2: "KOTA SAWAHLUNTO, BANTEN, ID, 64134" },
  { line1: "Gg. Surapati No. 1, Ville", line2: "KOTA MEDAN, MALUKU UTARA, ID, 36319" },
  { line1: "Gang Joyoboyo No. 7, Ville", line2: "KOTA MOJOKERTO, JAMBI, ID, 57462" },
  { line1: "Gang Dr. Djunjunan No. 650, Ville", line2: "KOTA MAGELANG, SULAWESI SELATAN, ID, 23973" },
  { line1: "Jalan Pelajar Pejuang No. 92, Ville", line2: "KOTA TEGAL, BALI, ID, 87051" },
  { line1: "Jalan Kebonjati No. 41, Ville", line2: "KOTA JAMBI, SULAWESI UTARA, ID, 99214" },
  { line1: "Jl. S. Parman No. 25, Ville", line2: "KOTA PURWOKERTO, NUSA TENGGARA TIMUR, ID, 49567" },
  { line1: "Gg. Ahmad Dahlan No. 3, Ville", line2: "KOTA PADANG SIDEMPUAN, KALIMANTAN TENGAH, ID, 30369" },
  { line1: "Jalan Dr. Djunjunan No. 01, Ville", line2: "KOTA MATARAM, KALIMANTAN UTARA, ID, 84483" },
  { line1: "Jalan S. Parman No. 2, Ville", line2: "KOTA PALU, GORONTALO, ID, 82256" },
  { line1: "Jl. Soekarno Hatta No. 995, Ville", line2: "KOTA YOGYAKARTA, GORONTALO, ID, 86653" },
  { line1: "Gang Sentot Alibasa No. 5, Ville", line2: "KOTA BANJARMASIN, DKI JAKARTA, ID, 10945" },
  { line1: "Gang Jamika No. 869, Ville", line2: "KOTA SUKABUMI, KEPULAUAN BANGKA BELITUNG, ID, 78675" },
  { line1: "Jalan Setiabudhi No. 74, Ville", line2: "KOTA KENDARI, JAWA TENGAH, ID, 57224" },
  { line1: "Gg. Merdeka No. 0, Ville", line2: "KOTA BANDUNG, SUMATERA UTARA, ID, 10074" },
  { line1: "Gang Pasir Koja No. 93, Ville", line2: "KOTA BATU, SULAWESI TENGGARA, ID, 49898" },
  { line1: "Gg. Asia Afrika No. 73, Ville", line2: "KOTA PALEMBANG, JAMBI, ID, 17181" },
  { line1: "Gang Erlangga No. 53, Ville", line2: "KOTA TASIKMALAYA, KALIMANTAN UTARA, ID, 93763" },
  { line1: "Gg. PHH. Mustofa No. 630, Ville", line2: "KOTA PEKALONGAN, MALUKU, ID, 49604" },
  { line1: "Jl. Ir. H. Djuanda No. 2, Ville", line2: "KOTA SUBULUSSALAM, ACEH, ID, 26890" },
  { line1: "Gang S. Parman No. 521, Ville", line2: "KOTA PROBOLINGGO, DI YOGYAKARTA, ID, 94475" },
  { line1: "Jl. Pasir Koja No. 4, Ville", line2: "KOTA TASIKMALAYA, ACEH, ID, 63599" },
  { line1: "Gang HOS. Cokroaminoto No. 594, Ville", line2: "KOTA PAGARALAM, SULAWESI TENGAH, ID, 47434" },
  { line1: "Jl. Monginsidi No. 432, Ville", line2: "KOTA LANGSA, NUSA TENGGARA BARAT, ID, 87338" },
  { line1: "Jalan S. Parman No. 726, Ville", line2: "KOTA GORONTALO, KALIMANTAN TIMUR, ID, 17879" },
  { line1: "Gang Antapani Lama No. 923, Ville", line2: "KOTA BITUNG, KALIMANTAN TIMUR, ID, 71181" },
  { line1: "Jl. Raya Ujungberung No. 24, Ville", line2: "KOTA SUKABUMI, BANTEN, ID, 43549" },
  { line1: "Gg. Tebet Barat Dalam No. 9, Ville", line2: "KOTA PROBOLINGGO, LAMPUNG, ID, 63541" },
  { line1: "Gg. Rumah Sakit No. 5, Ville", line2: "KOTA KOTAMOBAGU, KEPULAUAN BANGKA BELITUNG, ID, 52677" },
  { line1: "Gang HOS. Cokroaminoto No. 2, Ville", line2: "KOTA SUKABUMI, DKI JAKARTA, ID, 88163" },
  { line1: "Jl. Tubagus Ismail No. 9, Ville", line2: "KOTA SURAKARTA, KALIMANTAN UTARA, ID, 82939" },
  { line1: "Jalan Pelajar Pejuang No. 008, Ville", line2: "KOTA TERNATE, KALIMANTAN UTARA, ID, 52971" },
  { line1: "Jl. Moch. Toha No. 66, Ville", line2: "KOTA TANGERANG SELATAN, LAMPUNG, ID, 21829" },
  { line1: "Gg. Cikutra Barat No. 265, Ville", line2: "KOTA PAREPARE, KEPULAUAN RIAU, ID, 55507" },
  { line1: "Gg. M.T Haryono No. 81, Ville", line2: "KOTA SINGKAWANG, SULAWESI TENGGARA, ID, 54205" },
  { line1: "Jalan Dipatiukur No. 4, Ville", line2: "KOTA BANDA ACEH, KEPULAUAN RIAU, ID, 80786" },
  { line1: "Gang Rungkut Industri No. 47, Ville", line2: "KOTA TANJUNGPINANG, PAPUA BARAT, ID, 32760" },
  { line1: "Jl. Ahmad Dahlan No. 4, Ville", line2: "KOTA SUNGAI PENUH, JAWA BARAT, ID, 09040" },
  { line1: "Jalan Dipenogoro No. 1, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA TIMUR, MALUKU, ID, 01278" },
  { line1: "Jalan Gardujati No. 1, Ville", line2: "KOTA BANDAR LAMPUNG, KEPULAUAN BANGKA BELITUNG, ID, 28231" },
  { line1: "Gg. M.H Thamrin No. 314, Ville", line2: "KOTA MEULABOH, SULAWESI BARAT, ID, 36073" },
  { line1: "Gg. Siliwangi No. 276, Ville", line2: "KOTA METRO, DKI JAKARTA, ID, 38765" },
  { line1: "Jl. Rungkut Industri No. 808, Ville", line2: "KOTA JAYAPURA, JAMBI, ID, 91875" },
  { line1: "Gg. BKR No. 178, Ville", line2: "KOTA BALIKPAPAN, PAPUA, ID, 27547" },
  { line1: "Jalan Raya Setiabudhi No. 13, Ville", line2: "KOTA PALEMBANG, MALUKU, ID, 78365" },
  { line1: "Jalan Cihampelas No. 960, Ville", line2: "KOTA TANGERANG SELATAN, JAWA TENGAH, ID, 04561" },
  { line1: "Jl. Dipatiukur No. 53, Ville", line2: "KOTA BINJAI, KALIMANTAN SELATAN, ID, 21291" },
  { line1: "Gang M.H Thamrin No. 281, Ville", line2: "KOTA SUNGAI PENUH, JAWA TENGAH, ID, 08264" },
  { line1: "Jl. Monginsidi No. 74, Ville", line2: "KOTA TEBINGTINGGI, KALIMANTAN UTARA, ID, 91007" },
  { line1: "Jl. Lembong No. 052, Ville", line2: "KOTA SAWAHLUNTO, SUMATERA UTARA, ID, 06083" },
  { line1: "Gg. Jayawijaya No. 1, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA SELATAN, KALIMANTAN BARAT, ID, 08153" },
  { line1: "Jl. Siliwangi No. 95, Ville", line2: "KOTA BANDA ACEH, LAMPUNG, ID, 63198" },
  { line1: "Jl. Joyoboyo No. 767, Ville", line2: "KOTA MALANG, SULAWESI BARAT, ID, 25407" },
  { line1: "Jalan Kutai No. 2, Ville", line2: "KOTA BOGOR, MALUKU UTARA, ID, 84067" },
  { line1: "Gang Gegerkalong Hilir No. 495, Ville", line2: "KOTA BONTANG, BANTEN, ID, 74197" },
  { line1: "Gg. Jend. Sudirman No. 45, Ville", line2: "KOTA LUBUKLINGGAU, GORONTALO, ID, 71700" },
  { line1: "Gg. Ronggowarsito No. 48, Ville", line2: "KOTA BANDAR LAMPUNG, SULAWESI BARAT, ID, 43283" },
  { line1: "Jl. Lembong No. 0, Ville", line2: "KOTA PURWOKERTO, MALUKU UTARA, ID, 11994" },
  { line1: "Jl. Gegerkalong Hilir No. 768, Ville", line2: "KOTA PARIAMAN, DI YOGYAKARTA, ID, 90331" },
  { line1: "Jalan Sentot Alibasa No. 806, Ville", line2: "KOTA BALIKPAPAN, BENGKULU, ID, 37816" },
  { line1: "Gang Tubagus Ismail No. 4, Ville", line2: "KOTA MATARAM, KEPULAUAN RIAU, ID, 85489" },
  { line1: "Gg. Cikutra Timur No. 93, Ville", line2: "KOTA SINGKAWANG, KEPULAUAN BANGKA BELITUNG, ID, 42739" },
  { line1: "Gang Kiaracondong No. 1, Ville", line2: "KOTA SUBULUSSALAM, GORONTALO, ID, 90662" },
  { line1: "Gg. Medokan Ayu No. 2, Ville", line2: "KOTA PRABUMULIH, PAPUA BARAT, ID, 13725" },
  { line1: "Jalan Cihampelas No. 40, Ville", line2: "KOTA DEPOK, MALUKU, ID, 00633" },
  { line1: "Jalan Rajawali Barat No. 2, Ville", line2: "KOTA PANGKALPINANG, SULAWESI TENGAH, ID, 76656" },
  { line1: "Gg. Kutisari Selatan No. 68, Ville", line2: "KOTA BANJARBARU, SULAWESI TENGGARA, ID, 80715" },
  { line1: "Jl. Asia Afrika No. 427, Ville", line2: "KOTA PADANG, ACEH, ID, 20013" },
  { line1: "Jl. Waringin No. 138, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA PUSAT, JAWA TENGAH, ID, 07484" },
  { line1: "Gang Rajiman No. 895, Ville", line2: "KOTA DENPASAR, KALIMANTAN UTARA, ID, 76789" },
  { line1: "Jalan Cikutra Timur No. 872, Ville", line2: "KOTA BANDUNG, JAWA BARAT, ID, 46924" },
  { line1: "Gg. Kutai No. 54, Ville", line2: "KOTA BEKASI, MALUKU, ID, 82580" },
  { line1: "Jl. Cihampelas No. 688, Ville", line2: "KOTA TERNATE, KALIMANTAN UTARA, ID, 40280" },
  { line1: "Gang Tebet Barat Dalam No. 575, Ville", line2: "KOTA TARAKAN, BANTEN, ID, 10580" },
  { line1: "Gang Erlangga No. 34, Ville", line2: "KOTA PASURUAN, KALIMANTAN UTARA, ID, 33214" },
  { line1: "Jalan Lembong No. 46, Ville", line2: "KOTA PEKALONGAN, JAWA TIMUR, ID, 44062" },
  { line1: "Gang Kutisari Selatan No. 0, Ville", line2: "KOTA PANGKALPINANG, KALIMANTAN TENGAH, ID, 48559" },
  { line1: "Gang Gedebage Selatan No. 5, Ville", line2: "KOTA SERANG, KEPULAUAN BANGKA BELITUNG, ID, 17929" },
  { line1: "Jl. Suniaraja No. 907, Ville", line2: "KOTA YOGYAKARTA, JAMBI, ID, 93855" },
  { line1: "Gang K.H. Wahid Hasyim No. 532, Ville", line2: "KOTA BATU, KEPULAUAN RIAU, ID, 24236" },
  { line1: "Jalan Ir. H. Djuanda No. 61, Ville", line2: "KOTA PRABUMULIH, KEPULAUAN RIAU, ID, 46261" },
  { line1: "Gang Wonoayu No. 3, Ville", line2: "KOTA SABANG, DI YOGYAKARTA, ID, 49010" },
  { line1: "Gg. Jamika No. 19, Ville", line2: "KOTA DEPOK, JAWA BARAT, ID, 09139" },
  { line1: "Jalan Gedebage Selatan No. 50, Ville", line2: "KOTA TANJUNGPINANG, BANTEN, ID, 63248" },
  { line1: "Gg. Setiabudhi No. 3, Ville", line2: "KOTA BENGKULU, MALUKU, ID, 72187" },
  { line1: "Gang Cihampelas No. 8, Ville", line2: "KOTA LANGSA, MALUKU, ID, 44174" },
  { line1: "Gang Ciumbuleuit No. 0, Ville", line2: "KOTA CILEGON, BANTEN, ID, 90886" },
  { line1: "Gg. Gardujati No. 0, Ville", line2: "KOTA BATU, MALUKU UTARA, ID, 15580" },
  { line1: "Gg. Lembong No. 788, Ville", line2: "KOTA SAMARINDA, SUMATERA SELATAN, ID, 11145" },
  { line1: "Gang Sukabumi No. 754, Ville", line2: "KOTA TASIKMALAYA, KALIMANTAN UTARA, ID, 93534" },
  { line1: "Jl. Rumah Sakit No. 084, Ville", line2: "KOTA PADANG, PAPUA BARAT, ID, 94871" },
  { line1: "Gang Moch. Toha No. 997, Ville", line2: "KOTA BITUNG, KALIMANTAN SELATAN, ID, 71042" },
  { line1: "Jl. Siliwangi No. 642, Ville", line2: "KOTA BANJARBARU, JAWA TIMUR, ID, 53796" },
  { line1: "Gg. Yos Sudarso No. 085, Ville", line2: "KOTA MEDAN, JAWA BARAT, ID, 94157" },
  { line1: "Gg. M.T Haryono No. 05, Ville", line2: "KOTA BINJAI, SULAWESI TENGAH, ID, 70188" },
  { line1: "Jl. Kendalsari No. 85, Ville", line2: "KOTA BANJAR, MALUKU UTARA, ID, 80298" },
  { line1: "Jalan Ir. H. Djuanda No. 2, Ville", line2: "KOTA BENGKULU, DKI JAKARTA, ID, 69798" },
  { line1: "Jalan Rajawali Barat No. 62, Ville", line2: "KOTA MATARAM, JAWA TIMUR, ID, 41082" },
  { line1: "Gang W.R. Supratman No. 264, Ville", line2: "KOTA JAMBI, KEPULAUAN BANGKA BELITUNG, ID, 58180" },
  { line1: "Gang Kutisari Selatan No. 08, Ville", line2: "KOTA TOMOHON, JAMBI, ID, 39245" },
  { line1: "Jalan H.J Maemunah No. 717, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA PUSAT, BENGKULU, ID, 14596" },
  { line1: "Jl. Suryakencana No. 447, Ville", line2: "KOTA PEMATANGSIANTAR, BALI, ID, 60626" },
  { line1: "Gang Pelajar Pejuang No. 47, Ville", line2: "KOTA DENPASAR, PAPUA, ID, 19470" },
  { line1: "Gg. Kebonjati No. 36, Ville", line2: "KOTA PANGKALPINANG, KEPULAUAN BANGKA BELITUNG, ID, 35903" },
  { line1: "Gg. Dipenogoro No. 992, Ville", line2: "KOTA BANJAR, LAMPUNG, ID, 34123" },
  { line1: "Gang Sukabumi No. 97, Ville", line2: "KOTA PADANG, LAMPUNG, ID, 66804" },
  { line1: "Jalan Pasirkoja No. 2, Ville", line2: "KOTA PAGARALAM, SULAWESI BARAT, ID, 56567" },
  { line1: "Gg. Kutisari Selatan No. 021, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA PUSAT, JAWA TENGAH, ID, 72328" },
  { line1: "Gg. Pasteur No. 725, Ville", line2: "KOTA KENDARI, BALI, ID, 38815" },
  { line1: "Jl. Lembong No. 5, Ville", line2: "KOTA AMBON, ACEH, ID, 45082" },
  { line1: "Jalan Wonoayu No. 74, Ville", line2: "KOTA BUKITTINGGI, BANTEN, ID, 39536" },
  { line1: "Gg. Rawamangun No. 2, Ville", line2: "KOTA PARIAMAN, SUMATERA BARAT, ID, 86712" },
  { line1: "Jl. Cempaka No. 019, Ville", line2: "KOTA BANDAR LAMPUNG, SUMATERA SELATAN, ID, 85591" },
  { line1: "Jl. Jend. A. Yani No. 6, Ville", line2: "KOTA SAWAHLUNTO, NUSA TENGGARA TIMUR, ID, 99738" },
  { line1: "Gang Otto Iskandardinata No. 686, Ville", line2: "KOTA SALATIGA, BENGKULU, ID, 91944" },
  { line1: "Gang Wonoayu No. 6, Ville", line2: "KOTA PEKANBARU, SUMATERA SELATAN, ID, 57666" },
  { line1: "Gang Gegerkalong Hilir No. 371, Ville", line2: "KOTA PALEMBANG, BALI, ID, 56131" },
  { line1: "Jalan Astana Anyar No. 6, Ville", line2: "KOTA JAYAPURA, PAPUA BARAT, ID, 30019" },
  { line1: "Jl. K.H. Wahid Hasyim No. 2, Ville", line2: "KOTA CIREBON, GORONTALO, ID, 61081" },
  { line1: "Jalan Kutisari Selatan No. 66, Ville", line2: "KOTA DUMAI, MALUKU UTARA, ID, 64629" },
  { line1: "Jalan Medokan Ayu No. 50, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA UTARA, PAPUA BARAT, ID, 97788" },
  { line1: "Gang Kapten Muslihat No. 9, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA BARAT, SUMATERA SELATAN, ID, 94601" },
  { line1: "Jl. Abdul Muis No. 0, Ville", line2: "KOTA MEULABOH, SUMATERA BARAT, ID, 80407" },
  { line1: "Jalan Setiabudhi No. 2, Ville", line2: "KOTA PEKALONGAN, KALIMANTAN UTARA, ID, 51576" },
  { line1: "Jl. Ronggowarsito No. 67, Ville", line2: "KOTA BAU-BAU, MALUKU, ID, 33110" },
  { line1: "Jl. H.J Maemunah No. 9, Ville", line2: "KOTA BAU-BAU, NUSA TENGGARA BARAT, ID, 57608" },
  { line1: "Gg. Kutai No. 2, Ville", line2: "KOTA SURAKARTA, SUMATERA UTARA, ID, 75912" },
  { line1: "Gg. Joyoboyo No. 312, Ville", line2: "KOTA PAREPARE, MALUKU, ID, 18785" },
  { line1: "Gg. Pasirkoja No. 088, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA PUSAT, KALIMANTAN SELATAN, ID, 70785" },
  { line1: "Gang Setiabudhi No. 341, Ville", line2: "KOTA SEMARANG, DKI JAKARTA, ID, 38726" },
  { line1: "Gang Rajawali Barat No. 436, Ville", line2: "KOTA GORONTALO, SUMATERA UTARA, ID, 55767" },
  { line1: "Jl. Cikapayang No. 3, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA BARAT, KALIMANTAN TENGAH, ID, 06134" },
  { line1: "Gang Sadang Serang No. 5, Ville", line2: "KOTA PADANG SIDEMPUAN, JAWA TIMUR, ID, 19809" },
  { line1: "Gg. Dr. Djunjunan No. 044, Ville", line2: "KOTA BALIKPAPAN, ACEH, ID, 36965" },
  { line1: "Jalan Raya Ujungberung No. 2, Ville", line2: "KOTA BANJARMASIN, SUMATERA UTARA, ID, 67612" },
  { line1: "Gang Peta No. 42, Ville", line2: "KOTA BITUNG, SULAWESI TENGGARA, ID, 06393" },
  { line1: "Jalan Rumah Sakit No. 4, Ville", line2: "KOTA BLITAR, JAMBI, ID, 92391" },
  { line1: "Gg. W.R. Supratman No. 2, Ville", line2: "KOTA SUKABUMI, KALIMANTAN UTARA, ID, 53888" },
  { line1: "Jalan Kutai No. 647, Ville", line2: "KOTA MAKASSAR, DI YOGYAKARTA, ID, 44602" },
  { line1: "Gg. Gedebage Selatan No. 232, Ville", line2: "KOTA MEULABOH, RIAU, ID, 02811" },
  { line1: "Jalan Kiaracondong No. 36, Ville", line2: "KOTA AMBON, GORONTALO, ID, 89057" },
  { line1: "Jl. Tubagus Ismail No. 09, Ville", line2: "KOTA PADANG, MALUKU UTARA, ID, 70953" },
  { line1: "Jl. Astana Anyar No. 439, Ville", line2: "KOTA MATARAM, SUMATERA BARAT, ID, 49394" },
  { line1: "Gang Pasirkoja No. 0, Ville", line2: "KOTA TASIKMALAYA, KALIMANTAN TIMUR, ID, 05124" },
  { line1: "Jalan H.J Maemunah No. 725, Ville", line2: "KOTA CIREBON, KALIMANTAN UTARA, ID, 11073" },
  { line1: "Gang Jamika No. 8, Ville", line2: "KOTA SORONG, GORONTALO, ID, 81443" },
  { line1: "Jalan Raya Setiabudhi No. 014, Ville", line2: "KOTA TANJUNGBALAI, ACEH, ID, 97566" },
  { line1: "Gang Cihampelas No. 196, Ville", line2: "KOTA MALANG, DI YOGYAKARTA, ID, 77692" },
  { line1: "Jl. Dr. Djunjunan No. 688, Ville", line2: "KOTA SURABAYA, BANTEN, ID, 74451" },
  { line1: "Gg. Ciwastra No. 50, Ville", line2: "KOTA PARIAMAN, KALIMANTAN BARAT, ID, 42367" },
  { line1: "Gg. Bangka Raya No. 775, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA PUSAT, DKI JAKARTA, ID, 96645" },
  { line1: "Jl. Indragiri No. 861, Ville", line2: "KOTA MEDAN, SULAWESI SELATAN, ID, 43409" },
  { line1: "Gg. M.H Thamrin No. 655, Ville", line2: "KOTA PALU, SULAWESI TENGAH, ID, 66044" },
  { line1: "Gg. R.E Martadinata No. 4, Ville", line2: "KOTA MATARAM, KALIMANTAN TIMUR, ID, 99444" },
  { line1: "Jalan Ciwastra No. 14, Ville", line2: "KOTA BANJARBARU, MALUKU, ID, 44892" },
  { line1: "Gg. Peta No. 99, Ville", line2: "KOTA KENDARI, KALIMANTAN TIMUR, ID, 07261" },
  { line1: "Jl. Cihampelas No. 185, Ville", line2: "KOTA SUBULUSSALAM, PAPUA, ID, 85369" },
  { line1: "Gang Dipenogoro No. 14, Ville", line2: "KOTA PONTIANAK, SUMATERA SELATAN, ID, 92702" },
  { line1: "Gang Kebonjati No. 8, Ville", line2: "KOTA BIMA, SUMATERA BARAT, ID, 54122" },
  { line1: "Jalan Sadang Serang No. 38, Ville", line2: "KOTA MAKASSAR, KALIMANTAN SELATAN, ID, 68920" },
  { line1: "Jalan S. Parman No. 7, Ville", line2: "KOTA PADANG, KEPULAUAN BANGKA BELITUNG, ID, 83214" },
  { line1: "Gg. Abdul Muis No. 9, Ville", line2: "KOTA BEKASI, NUSA TENGGARA TIMUR, ID, 92848" },
  { line1: "Gang Yos Sudarso No. 079, Ville", line2: "KOTA KOTAMOBAGU, BANTEN, ID, 92042" },
  { line1: "Gg. Raya Ujungberung No. 500, Ville", line2: "KOTA LHOKSEUMAWE, JAWA TENGAH, ID, 53375" },
  { line1: "Jl. S. Parman No. 366, Ville", line2: "KOTA JAYAPURA, KALIMANTAN SELATAN, ID, 48444" },
  { line1: "Jalan Cihampelas No. 30, Ville", line2: "KOTA SURAKARTA, PAPUA BARAT, ID, 82137" },
  { line1: "Jalan Kendalsari No. 13, Ville", line2: "KOTA MOJOKERTO, SUMATERA BARAT, ID, 85556" },
  { line1: "Jalan Ciwastra No. 416, Ville", line2: "KOTA SURABAYA, RIAU, ID, 44833" },
  { line1: "Gang Medokan Ayu No. 58, Ville", line2: "KOTA GORONTALO, MALUKU, ID, 31350" },
  { line1: "Jl. Kapten Muslihat No. 36, Ville", line2: "KOTA BANDA ACEH, KALIMANTAN TIMUR, ID, 05899" },
  { line1: "Jl. Pasteur No. 9, Ville", line2: "KOTA SURAKARTA, DI YOGYAKARTA, ID, 09640" },
  { line1: "Jalan W.R. Supratman No. 729, Ville", line2: "KOTA SAMARINDA, KALIMANTAN BARAT, ID, 51653" },
  { line1: "Jl. Wonoayu No. 703, Ville", line2: "KOTA KOTAMOBAGU, PAPUA, ID, 45190" },
  { line1: "Jl. Astana Anyar No. 71, Ville", line2: "KOTA BANJARMASIN, SULAWESI BARAT, ID, 70286" },
  { line1: "Gang Merdeka No. 720, Ville", line2: "KOTA JAMBI, SUMATERA BARAT, ID, 15974" },
  { line1: "Jalan Pacuan Kuda No. 45, Ville", line2: "KOTA BATAM, NUSA TENGGARA TIMUR, ID, 38372" },
  { line1: "Jl. Sentot Alibasa No. 5, Ville", line2: "KOTA MEULABOH, PAPUA BARAT, ID, 37227" },
  { line1: "Gg. Jend. Sudirman No. 667, Ville", line2: "KOTA SINGKAWANG, JAMBI, ID, 41983" },
  { line1: "Jl. M.T Haryono No. 96, Ville", line2: "KOTA PONTIANAK, KEPULAUAN BANGKA BELITUNG, ID, 64391" },
  { line1: "Gg. Gedebage Selatan No. 693, Ville", line2: "KOTA KENDARI, PAPUA, ID, 81873" },
  { line1: "Gang Kutisari Selatan No. 6, Ville", line2: "KOTA PALOPO, BALI, ID, 06225" },
  { line1: "Jalan Merdeka No. 0, Ville", line2: "KOTA TASIKMALAYA, PAPUA BARAT, ID, 45034" },
  { line1: "Gg. Surapati No. 08, Ville", line2: "KOTA MATARAM, SUMATERA SELATAN, ID, 73256" },
  { line1: "Gg. Monginsidi No. 9, Ville", line2: "KOTA BANJAR, BALI, ID, 45025" },
  { line1: "Gg. M.T Haryono No. 021, Ville", line2: "KOTA TEBINGTINGGI, NUSA TENGGARA TIMUR, ID, 16185" },
  { line1: "Gang Pasirkoja No. 67, Ville", line2: "KOTA SUBULUSSALAM, SUMATERA UTARA, ID, 11214" },
  { line1: "Jalan Cikutra Timur No. 147, Ville", line2: "KOTA CILEGON, PAPUA, ID, 31371" },
  { line1: "Jl. Moch. Toha No. 39, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA BARAT, KALIMANTAN SELATAN, ID, 81596" },
  { line1: "Jl. Dipenogoro No. 14, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA SELATAN, SULAWESI UTARA, ID, 18499" },
  { line1: "Jalan Otto Iskandardinata No. 575, Ville", line2: "KOTA BAU-BAU, LAMPUNG, ID, 41274" },
  { line1: "Gg. M.T Haryono No. 9, Ville", line2: "KOTA BITUNG, PAPUA, ID, 77489" },
  { line1: "Gang PHH. Mustofa No. 0, Ville", line2: "KOTA PARIAMAN, SUMATERA BARAT, ID, 82737" },
  { line1: "Jalan Gedebage Selatan No. 380, Ville", line2: "KOTA AMBON, JAWA TIMUR, ID, 79474" },
  { line1: "Gang Ciumbuleuit No. 89, Ville", line2: "KOTA AMBON, DKI JAKARTA, ID, 65830" },
  { line1: "Jalan Monginsidi No. 3, Ville", line2: "KOTA TASIKMALAYA, MALUKU UTARA, ID, 35104" },
  { line1: "Gg. Moch. Toha No. 881, Ville", line2: "KOTA PAGARALAM, KALIMANTAN BARAT, ID, 09123" },
  { line1: "Gg. Pasirkoja No. 344, Ville", line2: "KOTA SAMARINDA, RIAU, ID, 47003" },
  { line1: "Jalan Gedebage Selatan No. 901, Ville", line2: "KOTA SEMARANG, JAWA TIMUR, ID, 07066" },
  { line1: "Gg. Pasteur No. 5, Ville", line2: "KOTA TIDORE KEPULAUAN, GORONTALO, ID, 06581" },
  { line1: "Gang Siliwangi No. 3, Ville", line2: "KOTA TOMOHON, NUSA TENGGARA TIMUR, ID, 34404" },
  { line1: "Jalan Cihampelas No. 3, Ville", line2: "KOTA PURWOKERTO, SULAWESI TENGAH, ID, 19146" },
  { line1: "Jl. Dr. Djunjunan No. 6, Ville", line2: "KOTA BAU-BAU, SULAWESI UTARA, ID, 09541" },
  { line1: "Gg. Sukajadi No. 797, Ville", line2: "KOTA BANJARBARU, DI YOGYAKARTA, ID, 96661" },
  { line1: "Jalan Dipatiukur No. 58, Ville", line2: "KOTA SOLOK, BENGKULU, ID, 77049" },
  { line1: "Gang Yos Sudarso No. 430, Ville", line2: "KOTA PEKANBARU, BANTEN, ID, 50794" },
  { line1: "Gg. Cikutra Timur No. 723, Ville", line2: "KOTA PONTIANAK, KALIMANTAN TENGAH, ID, 22890" },
  { line1: "Gg. PHH. Mustofa No. 937, Ville", line2: "KOTA BANJARBARU, KALIMANTAN TENGAH, ID, 24792" },
  { line1: "Gang M.H Thamrin No. 28, Ville", line2: "KOTA DEPOK, NUSA TENGGARA TIMUR, ID, 45285" },
  { line1: "Jalan Cihampelas No. 232, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA UTARA, ACEH, ID, 38380" },
  { line1: "Gg. Ir. H. Djuanda No. 8, Ville", line2: "KOTA TANGERANG SELATAN, NUSA TENGGARA BARAT, ID, 62230" },
  { line1: "Gang Raya Ujungberung No. 3, Ville", line2: "KOTA TEBINGTINGGI, PAPUA BARAT, ID, 39788" },
  { line1: "Gang Moch. Toha No. 6, Ville", line2: "KOTA BITUNG, SULAWESI SELATAN, ID, 64952" },
  { line1: "Jalan Wonoayu No. 171, Ville", line2: "KOTA PROBOLINGGO, GORONTALO, ID, 44337" },
  { line1: "Jalan Cihampelas No. 589, Ville", line2: "KOTA MAGELANG, DKI JAKARTA, ID, 74447" },
  { line1: "Gang Ronggowarsito No. 20, Ville", line2: "KOTA TOMOHON, SUMATERA SELATAN, ID, 13484" },
  { line1: "Gg. Stasiun Wonokromo No. 36, Ville", line2: "KOTA TEGAL, SUMATERA BARAT, ID, 17960" },
  { line1: "Gg. Sukajadi No. 743, Ville", line2: "KOTA PAGARALAM, KALIMANTAN UTARA, ID, 17043" },
  { line1: "Gang Rajawali Barat No. 82, Ville", line2: "KOTA PALU, KEPULAUAN BANGKA BELITUNG, ID, 03337" },
  { line1: "Jl. Waringin No. 56, Ville", line2: "KOTA BITUNG, DI YOGYAKARTA, ID, 56652" },
  { line1: "Gg. Monginsidi No. 29, Ville", line2: "KOTA TIDORE KEPULAUAN, MALUKU UTARA, ID, 42555" },
  { line1: "Gg. Medokan Ayu No. 4, Ville", line2: "KOTA BANJAR, KALIMANTAN BARAT, ID, 23271" },
  { line1: "Gg. Pacuan Kuda No. 74, Ville", line2: "KOTA CIMAHI, BANTEN, ID, 21555" },
  { line1: "Gang Sentot Alibasa No. 4, Ville", line2: "KOTA SAWAHLUNTO, JAMBI, ID, 27234" },
  { line1: "Jalan Ahmad Yani No. 36, Ville", line2: "KOTA SOLOK, JAWA TENGAH, ID, 79562" },
  { line1: "Gang Kapten Muslihat No. 2, Ville", line2: "KOTA PADANG SIDEMPUAN, SULAWESI BARAT, ID, 06860" },
  { line1: "Gg. Raya Ujungberung No. 84, Ville", line2: "KOTA BANDUNG, JAMBI, ID, 94597" },
  { line1: "Gang Monginsidi No. 081, Ville", line2: "KOTA MANADO, KALIMANTAN TIMUR, ID, 81438" },
  { line1: "Jl. Kutisari Selatan No. 735, Ville", line2: "KOTA PALANGKARAYA, KEPULAUAN RIAU, ID, 13466" },
  { line1: "Gg. Moch. Toha No. 95, Ville", line2: "KOTA CIMAHI, DI YOGYAKARTA, ID, 39451" },
  { line1: "Jl. Tebet Barat Dalam No. 408, Ville", line2: "KOTA BENGKULU, JAWA TENGAH, ID, 50348" },
  { line1: "Jl. Kiaracondong No. 411, Ville", line2: "KOTA TEBINGTINGGI, KALIMANTAN TIMUR, ID, 26830" },
  { line1: "Jalan Pasirkoja No. 352, Ville", line2: "KOTA PRABUMULIH, KALIMANTAN TENGAH, ID, 67972" },
  { line1: "Jl. Rajiman No. 3, Ville", line2: "KOTA BATAM, MALUKU, ID, 42080" },
  { line1: "Gang Rajawali Timur No. 087, Ville", line2: "KOTA TUAL, NUSA TENGGARA BARAT, ID, 91888" },
  { line1: "Jl. R.E Martadinata No. 33, Ville", line2: "KOTA MAGELANG, KALIMANTAN BARAT, ID, 24452" },
  { line1: "Jl. Merdeka No. 817, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA UTARA, KALIMANTAN BARAT, ID, 82826" },
  { line1: "Jalan Antapani Lama No. 35, Ville", line2: "KOTA TUAL, MALUKU UTARA, ID, 43396" },
  { line1: "Gang Pasir Koja No. 259, Ville", line2: "KOTA SOLOK, JAWA TIMUR, ID, 81937" },
  { line1: "Gang Rungkut Industri No. 493, Ville", line2: "KOTA PAREPARE, MALUKU UTARA, ID, 19946" },
  { line1: "Gg. Jend. A. Yani No. 14, Ville", line2: "KOTA PALEMBANG, JAMBI, ID, 26399" },
  { line1: "Jalan Pelajar Pejuang No. 081, Ville", line2: "KOTA PAYAKUMBUH, JAWA BARAT, ID, 06452" },
  { line1: "Jalan HOS. Cokroaminoto No. 3, Ville", line2: "KOTA BOGOR, NUSA TENGGARA TIMUR, ID, 38738" },
  { line1: "Jalan Pelajar Pejuang No. 156, Ville", line2: "KOTA PAREPARE, SULAWESI TENGGARA, ID, 11845" },
  { line1: "Gang Soekarno Hatta No. 82, Ville", line2: "KOTA SABANG, KALIMANTAN BARAT, ID, 92693" },
  { line1: "Jalan Tubagus Ismail No. 08, Ville", line2: "KOTA BANJARBARU, MALUKU, ID, 85133" },
  { line1: "Jl. Otto Iskandardinata No. 38, Ville", line2: "KOTA BALIKPAPAN, SULAWESI SELATAN, ID, 21772" },
  { line1: "Jalan Wonoayu No. 41, Ville", line2: "KOTA SALATIGA, SULAWESI UTARA, ID, 78936" },
  { line1: "Jl. Sadang Serang No. 052, Ville", line2: "KOTA SURABAYA, SULAWESI BARAT, ID, 82289" },
  { line1: "Gang Wonoayu No. 6, Ville", line2: "KOTA PARIAMAN, KEPULAUAN BANGKA BELITUNG, ID, 24307" },
  { line1: "Gang Otto Iskandardinata No. 5, Ville", line2: "KOTA PAGARALAM, PAPUA BARAT, ID, 00140" },
  { line1: "Gang Siliwangi No. 532, Ville", line2: "KOTA TIDORE KEPULAUAN, ACEH, ID, 12387" },
  { line1: "Jl. Cikapayang No. 51, Ville", line2: "KOTA SALATIGA, KALIMANTAN SELATAN, ID, 59623" },
  { line1: "Gang Jamika No. 137, Ville", line2: "KOTA BONTANG, LAMPUNG, ID, 61579" },
  { line1: "Jl. K.H. Wahid Hasyim No. 029, Ville", line2: "KOTA MAKASSAR, DI YOGYAKARTA, ID, 25929" },
  { line1: "Gang Stasiun Wonokromo No. 4, Ville", line2: "KOTA SURAKARTA, KALIMANTAN UTARA, ID, 67844" },
  { line1: "Gang Moch. Toha No. 558, Ville", line2: "KOTA BLITAR, JAWA TIMUR, ID, 84542" },
  { line1: "Jl. Gardujati No. 96, Ville", line2: "KOTA LHOKSEUMAWE, NUSA TENGGARA BARAT, ID, 50781" },
  { line1: "Jl. Rajiman No. 8, Ville", line2: "KOTA LHOKSEUMAWE, SULAWESI TENGGARA, ID, 22472" },
  { line1: "Jalan Lembong No. 98, Ville", line2: "KOTA CIREBON, NUSA TENGGARA BARAT, ID, 61079" },
  { line1: "Gang Rumah Sakit No. 6, Ville", line2: "KOTA SAMARINDA, SULAWESI SELATAN, ID, 46837" },
  { line1: "Gang Otto Iskandardinata No. 29, Ville", line2: "KOTA PAREPARE, GORONTALO, ID, 52360" },
  { line1: "Gg. Dipatiukur No. 4, Ville", line2: "KOTA BOGOR, BANTEN, ID, 52430" },
  { line1: "Jl. Pacuan Kuda No. 2, Ville", line2: "KOTA GORONTALO, DI YOGYAKARTA, ID, 38923" },
  { line1: "Jl. Raya Setiabudhi No. 74, Ville", line2: "KOTA METRO, PAPUA BARAT, ID, 77405" },
  { line1: "Jalan Dipenogoro No. 293, Ville", line2: "KOTA AMBON, JAWA TIMUR, ID, 72286" },
  { line1: "Jalan Surapati No. 301, Ville", line2: "KOTA BATAM, MALUKU, ID, 39126" },
  { line1: "Jalan Dipatiukur No. 80, Ville", line2: "KOTA TANGERANG, JAWA TENGAH, ID, 85402" },
  { line1: "Gang M.H Thamrin No. 04, Ville", line2: "KOTA CILEGON, KALIMANTAN TIMUR, ID, 00040" },
  { line1: "Gg. Ciwastra No. 967, Ville", line2: "KOTA PASURUAN, SULAWESI BARAT, ID, 57339" },
  { line1: "Gang Moch. Toha No. 77, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA PUSAT, SUMATERA UTARA, ID, 03378" },
  { line1: "Gang Rajawali Barat No. 111, Ville", line2: "KOTA SERANG, SULAWESI SELATAN, ID, 75486" },
  { line1: "Gang Gegerkalong Hilir No. 574, Ville", line2: "KOTA PADANG, LAMPUNG, ID, 34073" },
  { line1: "Gang Astana Anyar No. 533, Ville", line2: "KOTA PALANGKARAYA, KALIMANTAN BARAT, ID, 91115" },
  { line1: "Gang Surapati No. 220, Ville", line2: "KOTA PAGARALAM, NUSA TENGGARA BARAT, ID, 29134" },
  { line1: "Jalan Wonoayu No. 4, Ville", line2: "KOTA BLITAR, SULAWESI BARAT, ID, 08931" },
  { line1: "Jalan Abdul Muis No. 29, Ville", line2: "KOTA SUKABUMI, PAPUA BARAT, ID, 52311" },
  { line1: "Jl. Ir. H. Djuanda No. 3, Ville", line2: "KOTA MAGELANG, MALUKU, ID, 93829" },
  { line1: "Gang Joyoboyo No. 7, Ville", line2: "KOTA MOJOKERTO, BENGKULU, ID, 41741" },
  { line1: "Jl. Wonoayu No. 6, Ville", line2: "KOTA PAYAKUMBUH, SULAWESI BARAT, ID, 88154" },
  { line1: "Jl. Monginsidi No. 57, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA PUSAT, SUMATERA UTARA, ID, 35947" },
  { line1: "Gang Monginsidi No. 84, Ville", line2: "KOTA METRO, BANTEN, ID, 05158" },
  { line1: "Gg. HOS. Cokroaminoto No. 212, Ville", line2: "KOTA PARIAMAN, BENGKULU, ID, 84383" },
  { line1: "Jalan BKR No. 9, Ville", line2: "KOTA SINGKAWANG, NUSA TENGGARA TIMUR, ID, 11424" },
  { line1: "Jalan Peta No. 87, Ville", line2: "KOTA MEULABOH, BANTEN, ID, 21877" },
  { line1: "Gg. Raya Setiabudhi No. 7, Ville", line2: "KOTA BAU-BAU, PAPUA BARAT, ID, 41865" },
  { line1: "Gg. Indragiri No. 643, Ville", line2: "KOTA SALATIGA, MALUKU, ID, 83636" },
  { line1: "Gang Cikutra Barat No. 66, Ville", line2: "KOTA SAMARINDA, SULAWESI TENGGARA, ID, 66481" },
  { line1: "Jl. Pasir Koja No. 8, Ville", line2: "KOTA BOGOR, NUSA TENGGARA BARAT, ID, 28149" },
  { line1: "Gang Ahmad Dahlan No. 839, Ville", line2: "KOTA TERNATE, KEPULAUAN BANGKA BELITUNG, ID, 19797" },
  { line1: "Gang Sadang Serang No. 46, Ville", line2: "KOTA BANJARMASIN, PAPUA, ID, 94207" },
  { line1: "Gang Gedebage Selatan No. 683, Ville", line2: "KOTA SORONG, JAWA TIMUR, ID, 18423" },
  { line1: "Gang Otto Iskandardinata No. 9, Ville", line2: "KOTA SIBOLGA, MALUKU, ID, 00472" },
  { line1: "Jalan Bangka Raya No. 03, Ville", line2: "KOTA BLITAR, BANTEN, ID, 35973" },
  { line1: "Jalan Suniaraja No. 3, Ville", line2: "KOTA BATU, JAWA TENGAH, ID, 29091" },
  { line1: "Gg. HOS. Cokroaminoto No. 6, Ville", line2: "KOTA BITUNG, SULAWESI UTARA, ID, 02149" },
  { line1: "Jl. Ciwastra No. 89, Ville", line2: "KOTA PADANGPANJANG, JAWA TIMUR, ID, 50154" },
  { line1: "Gang Kapten Muslihat No. 29, Ville", line2: "KOTA PALANGKARAYA, SUMATERA BARAT, ID, 14923" },
  { line1: "Jl. Suryakencana No. 012, Ville", line2: "KOTA PEKANBARU, SUMATERA UTARA, ID, 15329" },
  { line1: "Gang Rajawali Timur No. 23, Ville", line2: "KOTA BOGOR, BALI, ID, 43190" },
  { line1: "Jalan Kutisari Selatan No. 5, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA TIMUR, SUMATERA UTARA, ID, 85160" },
  { line1: "Gang Medokan Ayu No. 80, Ville", line2: "KOTA SUKABUMI, GORONTALO, ID, 02472" },
  { line1: "Jl. Dr. Djunjunan No. 695, Ville", line2: "KOTA SABANG, JAWA TIMUR, ID, 47864" },
  { line1: "Jalan Abdul Muis No. 23, Ville", line2: "KOTA BEKASI, PAPUA, ID, 25602" },
  { line1: "Gang Pacuan Kuda No. 08, Ville", line2: "KOTA PALANGKARAYA, ACEH, ID, 26976" },
  { line1: "Jl. Kiaracondong No. 26, Ville", line2: "KOTA PALANGKARAYA, MALUKU UTARA, ID, 79396" },
  { line1: "Gang Bangka Raya No. 069, Ville", line2: "KOTA BATAM, SULAWESI TENGGARA, ID, 44609" },
  { line1: "Gang Pasirkoja No. 18, Ville", line2: "KOTA PAREPARE, JAWA TIMUR, ID, 32158" },
  { line1: "Gang Bangka Raya No. 927, Ville", line2: "KOTA BANDUNG, SUMATERA UTARA, ID, 26956" },
  { line1: "Jl. Gegerkalong Hilir No. 11, Ville", line2: "KOTA SORONG, MALUKU, ID, 76354" },
  { line1: "Jalan Jayawijaya No. 6, Ville", line2: "KOTA PROBOLINGGO, SUMATERA UTARA, ID, 39237" },
  { line1: "Gg. Pasteur No. 517, Ville", line2: "KOTA SEMARANG, KALIMANTAN TIMUR, ID, 21239" },
  { line1: "Jl. Cikutra Timur No. 4, Ville", line2: "KOTA BONTANG, JAMBI, ID, 59910" },
  { line1: "Gg. Cihampelas No. 546, Ville", line2: "KOTA MOJOKERTO, BENGKULU, ID, 90186" },
  { line1: "Jalan Kutai No. 337, Ville", line2: "KOTA PADANGPANJANG, KALIMANTAN TENGAH, ID, 84926" },
  { line1: "Gang Surapati No. 751, Ville", line2: "KOTA SERANG, SUMATERA SELATAN, ID, 07742" },
  { line1: "Gang Sadang Serang No. 26, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA PUSAT, BENGKULU, ID, 90320" },
  { line1: "Jalan Jayawijaya No. 896, Ville", line2: "KOTA BIMA, SUMATERA BARAT, ID, 06007" },
  { line1: "Jalan Cikapayang No. 33, Ville", line2: "KOTA PARIAMAN, LAMPUNG, ID, 25898" },
  { line1: "Gg. Rumah Sakit No. 4, Ville", line2: "KOTA MAGELANG, SULAWESI BARAT, ID, 93543" },
  { line1: "Gg. Stasiun Wonokromo No. 063, Ville", line2: "KOTA BIMA, NUSA TENGGARA BARAT, ID, 61260" },
  { line1: "Jl. Jayawijaya No. 77, Ville", line2: "KOTA PASURUAN, MALUKU, ID, 89822" },
  { line1: "Jl. Dipatiukur No. 5, Ville", line2: "KOTA BANDUNG, DKI JAKARTA, ID, 61778" },
  { line1: "Gg. Raya Ujungberung No. 4, Ville", line2: "KOTA BEKASI, DI YOGYAKARTA, ID, 06948" },
  { line1: "Jalan Gardujati No. 099, Ville", line2: "KOTA LUBUKLINGGAU, SULAWESI SELATAN, ID, 18946" },
  { line1: "Jalan Cikapayang No. 0, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA UTARA, KALIMANTAN TIMUR, ID, 84108" },
  { line1: "Gang Tebet Barat Dalam No. 05, Ville", line2: "KOTA KOTA ADMINISTRASI JAKARTA UTARA, PAPUA, ID, 77025" },
  { line1: "Jalan KH Amin Jasuta No. 986, Ville", line2: "KOTA BIMA, JAMBI, ID, 65439" },
  { line1: "Gang Ahmad Dahlan No. 861, Ville", line2: "KOTA TEBINGTINGGI, SUMATERA SELATAN, ID, 61664" },
  { line1: "Jalan Pasirkoja No. 102, Ville", line2: "KOTA LUBUKLINGGAU, DKI JAKARTA, ID, 83356" },
  { line1: "Jalan Moch. Ramdan No. 792, Ville", line2: "KOTA SIBOLGA, MALUKU UTARA, ID, 81809" },
  { line1: "Gg. Suryakencana No. 105, Ville", line2: "KOTA SUBULUSSALAM, BALI, ID, 92512" },
  { line1: "Jalan Dr. Djunjunan No. 4, Ville", line2: "KOTA MEDAN, NUSA TENGGARA BARAT, ID, 50413" },
  { line1: "Gg. Wonoayu No. 4, Ville", line2: "KOTA TANJUNGPINANG, BANTEN, ID, 78019" },
  { line1: "Gg. Cihampelas No. 47, Ville", line2: "KOTA SURAKARTA, LAMPUNG, ID, 15749" },
  { line1: "Jl. Sukabumi No. 228, Ville", line2: "KOTA KOTAMOBAGU, BALI, ID, 42159" },
  { line1: "Gang Siliwangi No. 571, Ville", line2: "KOTA SUNGAI PENUH, SUMATERA BARAT, ID, 21682" },
  { line1: "Jl. Kutisari Selatan No. 7, Ville", line2: "KOTA SURABAYA, SUMATERA UTARA, ID, 08351" },
  { line1: "Jl. Pasir Koja No. 757, Ville", line2: "KOTA BATU, KALIMANTAN SELATAN, ID, 06338" },
  { line1: "Jl. Cikutra Timur No. 5, Ville", line2: "KOTA PAREPARE, RIAU, ID, 56854" },
  { line1: "Gang Pasirkoja No. 6, Ville", line2: "KOTA PARIAMAN, NUSA TENGGARA BARAT, ID, 79748" },
];