type Product = { name: string[]; variation: string; price: number };

export const products: Product[] = [
  { name: ["Paket Sayur Sop"], variation: "per kg", price: 77097 },
  { name: ["Jeruk Sunkist"], variation: "per buah (~2kg)", price: 31868 },
  { name: ["Paket Sayur Sop", "Ramah Lingkungan", "ECO"], variation: "per sisir", price: 115604 },
  { name: ["Mangga Harum Manis"], variation: "500 gr", price: 62314 },
  { name: ["Jeruk Sunkist", "ORGANIK", "Segar"], variation: "box 25 sachet", price: 147853 },
  { name: ["Wortel Berastagi"], variation: "pack 200 gr", price: 77926 },
  { name: ["Reusable Bag"], variation: "per buah (~2kg)", price: 115785 },
  { name: ["Tomat Ceri", "Premium"], variation: "per ikat", price: 93236 },
  { name: ["Apel Fuji"], variation: "botol 500ml", price: 30353 },
  { name: ["Tomat Ceri", "Fresh"], variation: "per kg", price: 125435 },
  { name: ["Jus Jambu Merah"], variation: "botol 500ml", price: 25656 },
  { name: ["Jus Jambu Merah", "Manis"], variation: "per sisir", price: 55407 },
  { name: ["Pisang Cavendish"], variation: "per kg", price: 64742 },
  { name: ["Reusable Bag", "ECO"], variation: "per ikat", price: 31476 },
  { name: ["Wortel Berastagi", "Tanpa Gula"], variation: "Ukuran Large", price: 100638 },
  { name: ["Durian Medan", "Manis"], variation: "per ikat", price: 74986 },
  { name: ["Pisang Cavendish", "ECO", "Premium"], variation: "1 paket", price: 69175 },
  { name: ["Durian Medan", "Impor"], variation: "pack 250 gr", price: 62570 },
  { name: ["Paket Sayur Sop", "ORGANIK"], variation: "per ikat", price: 13414 },
  { name: ["Reusable Bag", "Impor"], variation: "pack 250 gr", price: 22350 },
  { name: ["Jeruk Sunkist", "Manis", "Segar"], variation: "Ukuran Large", price: 135870 },
  { name: ["Wortel Berastagi", "Tanpa Gula", "Premium"], variation: "pack 250 gr", price: 41603 },
  { name: ["Jeruk Sunkist", "Ramah Lingkungan", "Fresh"], variation: "box 25 sachet", price: 117311 },
  { name: ["Teh Hijau", "Impor", "Manis"], variation: "per ikat", price: 41262 },
  { name: ["Jus Jambu Merah", "ECO"], variation: "per kg", price: 33743 },
  { name: ["Durian Medan", "Premium", "Impor"], variation: "per sisir", price: 21653 },
  { name: ["Wortel Berastagi", "Tanpa Gula"], variation: "1 paket", price: 70906 },
  { name: ["Jus Jambu Merah"], variation: "Ukuran Large", price: 35029 },
  { name: ["Paket Sayur Sop", "Fresh", "Manis"], variation: "500 gr", price: 81939 },
  { name: ["Wortel Berastagi"], variation: "pack 200 gr", price: 5850 },
  { name: ["Pisang Cavendish", "Fresh", "Premium"], variation: "1 paket", price: 32894 },
  { name: ["Madu Hutan Murni", "Fresh", "Segar"], variation: "per buah (~2kg)", price: 103019 },
  { name: ["Reusable Bag"], variation: "1 paket", price: 144029 },
  { name: ["Teh Hijau"], variation: "per sisir", price: 89975 },
  { name: ["Rujak Buah"], variation: "500 gr", price: 100153 },
  { name: ["Teh Hijau", "Segar"], variation: "per kg", price: 68143 },
  { name: ["Teh Hijau", "ECO", "Ramah Lingkungan"], variation: "box 25 sachet", price: 132399 },
  { name: ["Madu Hutan Murni"], variation: "1 paket", price: 37967 },
  { name: ["Durian Medan", "Tanpa Gula", "Premium"], variation: "pack 250 gr", price: 143326 },
  { name: ["Madu Hutan Murni", "Impor", "Segar"], variation: "1 paket", price: 57730 },
  { name: ["Pisang Cavendish", "Impor"], variation: "Ukuran Large", price: 102889 },
  { name: ["Rujak Buah", "Tanpa Gula", "ECO"], variation: "per ikat", price: 63903 },
  { name: ["Apel Fuji", "ORGANIK"], variation: "per sisir", price: 65323 },
  { name: ["Selada ORGANIK"], variation: "per kg", price: 23610 },
  { name: ["Pisang Cavendish", "ORGANIK", "Segar"], variation: "500 gr", price: 13234 },
  { name: ["Madu Hutan Murni", "ECO"], variation: "1 paket", price: 67391 },
  { name: ["Bayam Segar", "Tanpa Gula", "Segar"], variation: "1 paket", price: 39684 },
  { name: ["Pisang Cavendish", "Tanpa Gula", "Segar"], variation: "pack 200 gr", price: 111708 },
  { name: ["Jeruk Sunkist"], variation: "500 gr", price: 117997 },
  { name: ["Tomat Ceri", "Impor"], variation: "pack 200 gr", price: 19200 },
  { name: ["Paket Sayur Sop", "ECO", "ORGANIK"], variation: "botol 500ml", price: 93946 },
  { name: ["Reusable Bag"], variation: "per ikat", price: 55224 },
  { name: ["Jeruk Sunkist", "Tanpa Gula", "Premium"], variation: "botol 500ml", price: 53100 },
  { name: ["Bayam Segar", "Segar"], variation: "500 gr", price: 121164 },
  { name: ["Reusable Bag", "ECO", "ORGANIK"], variation: "Ukuran Large", price: 146711 },
  { name: ["Madu Hutan Murni"], variation: "500 gr", price: 66965 },
  { name: ["Durian Medan", "Tanpa Gula"], variation: "pack 200 gr", price: 61032 },
  { name: ["Madu Hutan Murni", "ORGANIK"], variation: "per buah (~2kg)", price: 104345 },
  { name: ["Mangga Harum Manis", "Fresh"], variation: "pack 200 gr", price: 79776 },
  { name: ["Wortel Berastagi", "Ramah Lingkungan", "Tanpa Gula"], variation: "per buah (~2kg)", price: 54780 },
  { name: ["Bayam Segar"], variation: "per kg", price: 147133 },
  { name: ["Mangga Harum Manis", "Manis", "ORGANIK"], variation: "per kg", price: 129987 },
  { name: ["Jus Jambu Merah", "Premium", "ORGANIK"], variation: "1 paket", price: 26000 },
  { name: ["Madu Hutan Murni"], variation: "500 gr", price: 22815 },
  { name: ["Paket Sayur Sop"], variation: "botol 500ml", price: 36427 },
  { name: ["Teh Hijau", "Segar", "ORGANIK"], variation: "per sisir", price: 26491 },
  { name: ["Wortel Berastagi", "Ramah Lingkungan", "Manis"], variation: "pack 250 gr", price: 58545 },
  { name: ["Paket Sayur Sop", "Manis", "Segar"], variation: "pack 250 gr", price: 108752 },
  { name: ["Durian Medan", "Fresh", "Tanpa Gula"], variation: "porsi besar", price: 24016 },
  { name: ["Mangga Harum Manis", "ECO"], variation: "500 gr", price: 145937 },
  { name: ["Jeruk Sunkist", "Fresh", "Premium"], variation: "porsi besar", price: 23033 },
  { name: ["Teh Hijau"], variation: "porsi besar", price: 79707 },
  { name: ["Durian Medan", "Ramah Lingkungan"], variation: "box 25 sachet", price: 84303 },
  { name: ["Selada ORGANIK", "Ramah Lingkungan", "ORGANIK"], variation: "Ukuran Large", price: 83480 },
  { name: ["Teh Hijau", "ECO", "Premium"], variation: "pack 250 gr", price: 35258 },
  { name: ["Teh Hijau"], variation: "box 25 sachet", price: 45749 },
  { name: ["Bayam Segar", "Segar"], variation: "box 25 sachet", price: 94884 },
  { name: ["Jeruk Sunkist", "Fresh", "Tanpa Gula"], variation: "pack 250 gr", price: 18316 },
  { name: ["Apel Fuji", "Impor", "Fresh"], variation: "per kg", price: 5929 },
  { name: ["Tomat Ceri"], variation: "Ukuran Large", price: 73670 },
  { name: ["Durian Medan", "Tanpa Gula", "Impor"], variation: "1 paket", price: 7534 },
  { name: ["Apel Fuji"], variation: "box 25 sachet", price: 44073 },
  { name: ["Jus Jambu Merah"], variation: "porsi besar", price: 149841 },
  { name: ["Durian Medan", "Premium"], variation: "per kg", price: 85808 },
  { name: ["Tomat Ceri"], variation: "porsi besar", price: 60070 },
  { name: ["Paket Sayur Sop"], variation: "Ukuran Large", price: 31946 },
  { name: ["Tomat Ceri", "Impor", "Premium"], variation: "per ikat", price: 47598 },
  { name: ["Reusable Bag"], variation: "botol 500ml", price: 11497 },
  { name: ["Durian Medan", "Manis", "Impor"], variation: "Ukuran Large", price: 70055 },
  { name: ["Bayam Segar"], variation: "box 25 sachet", price: 33336 },
  { name: ["Wortel Berastagi"], variation: "pack 200 gr", price: 63309 },
  { name: ["Jeruk Sunkist", "Manis"], variation: "pack 250 gr", price: 64662 },
  { name: ["Jeruk Sunkist"], variation: "Ukuran Large", price: 55627 },
  { name: ["Wortel Berastagi", "Fresh"], variation: "500 gr", price: 78170 },
  { name: ["Tomat Ceri", "Ramah Lingkungan", "Impor"], variation: "Ukuran Large", price: 145565 },
  { name: ["Tomat Ceri"], variation: "500 gr", price: 73475 },
  { name: ["Durian Medan", "Fresh", "ORGANIK"], variation: "500 gr", price: 118918 },
  { name: ["Tomat Ceri", "Manis", "Impor"], variation: "per sisir", price: 139066 },
  { name: ["Apel Fuji", "Segar"], variation: "pack 250 gr", price: 16635 },
  { name: ["Pisang Cavendish", "ORGANIK"], variation: "1 paket", price: 146151 },
  { name: ["Paket Sayur Sop", "Segar", "Manis"], variation: "botol 500ml", price: 23343 },
  { name: ["Paket Sayur Sop", "Manis"], variation: "Ukuran Large", price: 37669 },
  { name: ["Pisang Cavendish", "Ramah Lingkungan"], variation: "pack 250 gr", price: 112057 },
  { name: ["Tomat Ceri", "Fresh"], variation: "1 paket", price: 38367 },
  { name: ["Jeruk Sunkist", "Impor"], variation: "Ukuran Large", price: 50620 },
  { name: ["Selada ORGANIK", "Fresh", "Impor"], variation: "1 paket", price: 5106 },
  { name: ["Bayam Segar", "Segar"], variation: "botol 500ml", price: 89475 },
  { name: ["Rujak Buah", "Tanpa Gula"], variation: "Ukuran Large", price: 61020 },
  { name: ["Jus Jambu Merah", "Premium"], variation: "Ukuran Large", price: 27228 },
  { name: ["Bayam Segar", "Manis", "ECO"], variation: "per ikat", price: 86374 },
  { name: ["Jeruk Sunkist"], variation: "per buah (~2kg)", price: 11402 },
  { name: ["Mangga Harum Manis"], variation: "pack 200 gr", price: 24091 },
  { name: ["Rujak Buah", "Segar"], variation: "box 25 sachet", price: 105657 },
  { name: ["Rujak Buah", "Segar"], variation: "per buah (~2kg)", price: 6453 },
  { name: ["Teh Hijau"], variation: "botol 500ml", price: 62367 },
  { name: ["Durian Medan", "Ramah Lingkungan", "Tanpa Gula"], variation: "per kg", price: 70325 },
  { name: ["Teh Hijau"], variation: "pack 200 gr", price: 39954 },
  { name: ["Reusable Bag", "Ramah Lingkungan"], variation: "1 paket", price: 88177 },
  { name: ["Reusable Bag", "Ramah Lingkungan"], variation: "botol 500ml", price: 148621 },
  { name: ["Rujak Buah"], variation: "box 25 sachet", price: 129433 },
  { name: ["Rujak Buah", "Segar"], variation: "Ukuran Large", price: 77695 },
  { name: ["Reusable Bag", "Tanpa Gula", "Segar"], variation: "pack 250 gr", price: 120309 },
  { name: ["Apel Fuji", "Fresh", "Segar"], variation: "pack 250 gr", price: 93040 },
  { name: ["Tomat Ceri", "ECO", "Premium"], variation: "per buah (~2kg)", price: 65623 },
  { name: ["Wortel Berastagi", "Premium", "Segar"], variation: "500 gr", price: 113755 },
  { name: ["Wortel Berastagi", "Ramah Lingkungan"], variation: "pack 200 gr", price: 113992 },
  { name: ["Mangga Harum Manis"], variation: "botol 500ml", price: 107099 },
  { name: ["Teh Hijau", "ORGANIK", "Impor"], variation: "pack 200 gr", price: 6545 },
  { name: ["Tomat Ceri", "Impor"], variation: "botol 500ml", price: 146091 },
  { name: ["Pisang Cavendish", "Ramah Lingkungan", "Segar"], variation: "pack 200 gr", price: 62520 },
  { name: ["Bayam Segar", "Tanpa Gula"], variation: "per kg", price: 106936 },
  { name: ["Tomat Ceri", "Impor", "Premium"], variation: "pack 200 gr", price: 38456 },
  { name: ["Selada ORGANIK", "ORGANIK", "Impor"], variation: "per sisir", price: 12104 },
  { name: ["Apel Fuji", "Impor", "Premium"], variation: "pack 200 gr", price: 52639 },
  { name: ["Mangga Harum Manis", "Impor"], variation: "porsi besar", price: 60485 },
  { name: ["Rujak Buah", "Manis"], variation: "botol 500ml", price: 77943 },
  { name: ["Reusable Bag", "Fresh"], variation: "500 gr", price: 128288 },
  { name: ["Mangga Harum Manis", "Ramah Lingkungan", "ORGANIK"], variation: "porsi besar", price: 63778 },
  { name: ["Paket Sayur Sop"], variation: "Ukuran Large", price: 15553 },
  { name: ["Reusable Bag"], variation: "per ikat", price: 57261 },
  { name: ["Madu Hutan Murni"], variation: "per sisir", price: 44946 },
  { name: ["Jeruk Sunkist"], variation: "pack 200 gr", price: 34986 },
  { name: ["Selada ORGANIK"], variation: "pack 200 gr", price: 72172 },
  { name: ["Reusable Bag", "Premium"], variation: "per sisir", price: 35024 },
  { name: ["Reusable Bag"], variation: "pack 250 gr", price: 33337 },
  { name: ["Selada ORGANIK"], variation: "pack 250 gr", price: 103384 },
  { name: ["Wortel Berastagi", "Segar", "ECO"], variation: "per sisir", price: 68661 },
  { name: ["Apel Fuji", "Fresh", "ECO"], variation: "per sisir", price: 15766 },
  { name: ["Tomat Ceri", "Impor", "Manis"], variation: "500 gr", price: 137634 },
  { name: ["Paket Sayur Sop", "ORGANIK"], variation: "botol 500ml", price: 133503 },
  { name: ["Apel Fuji", "Manis"], variation: "Ukuran Large", price: 125517 },
  { name: ["Pisang Cavendish"], variation: "botol 500ml", price: 51173 },
  { name: ["Pisang Cavendish", "Fresh", "Tanpa Gula"], variation: "pack 200 gr", price: 119183 },
  { name: ["Madu Hutan Murni", "Fresh", "Manis"], variation: "per ikat", price: 27718 },
  { name: ["Bayam Segar", "Segar"], variation: "pack 200 gr", price: 104349 },
  { name: ["Tomat Ceri"], variation: "pack 200 gr", price: 90200 },
  { name: ["Durian Medan", "Segar"], variation: "porsi besar", price: 72725 },
  { name: ["Tomat Ceri", "Fresh"], variation: "1 paket", price: 7661 },
  { name: ["Jus Jambu Merah"], variation: "500 gr", price: 68270 },
  { name: ["Pisang Cavendish", "Tanpa Gula"], variation: "1 paket", price: 67999 },
  { name: ["Pisang Cavendish", "Tanpa Gula"], variation: "pack 200 gr", price: 9520 },
  { name: ["Apel Fuji", "Segar"], variation: "botol 500ml", price: 68780 },
  { name: ["Bayam Segar", "Manis", "Tanpa Gula"], variation: "1 paket", price: 144177 },
  { name: ["Tomat Ceri", "Ramah Lingkungan"], variation: "porsi besar", price: 97225 },
  { name: ["Pisang Cavendish", "Fresh"], variation: "pack 250 gr", price: 70903 },
  { name: ["Jeruk Sunkist"], variation: "box 25 sachet", price: 55484 },
  { name: ["Tomat Ceri"], variation: "box 25 sachet", price: 145473 },
  { name: ["Reusable Bag", "Premium", "Segar"], variation: "per ikat", price: 131929 },
  { name: ["Bayam Segar", "Ramah Lingkungan", "Fresh"], variation: "500 gr", price: 55886 },
  { name: ["Bayam Segar"], variation: "porsi besar", price: 52039 },
  { name: ["Bayam Segar"], variation: "box 25 sachet", price: 145020 },
  { name: ["Durian Medan", "ORGANIK"], variation: "per kg", price: 81581 },
  { name: ["Pisang Cavendish"], variation: "Ukuran Large", price: 133680 },
  { name: ["Apel Fuji"], variation: "per sisir", price: 79537 },
  { name: ["Rujak Buah", "Tanpa Gula"], variation: "porsi besar", price: 53329 },
  { name: ["Mangga Harum Manis", "Tanpa Gula"], variation: "500 gr", price: 22129 },
  { name: ["Wortel Berastagi", "ECO"], variation: "per sisir", price: 19053 },
  { name: ["Durian Medan"], variation: "per sisir", price: 84648 },
  { name: ["Apel Fuji"], variation: "500 gr", price: 114097 },
  { name: ["Selada ORGANIK", "Segar", "Impor"], variation: "pack 200 gr", price: 121056 },
  { name: ["Bayam Segar", "Impor", "Fresh"], variation: "per sisir", price: 20789 },
  { name: ["Selada ORGANIK", "ECO", "Segar"], variation: "Ukuran Large", price: 60318 },
  { name: ["Bayam Segar", "ECO", "Premium"], variation: "per ikat", price: 50564 },
  { name: ["Jus Jambu Merah"], variation: "per buah (~2kg)", price: 5701 },
  { name: ["Wortel Berastagi", "Tanpa Gula"], variation: "pack 250 gr", price: 13556 },
  { name: ["Jeruk Sunkist", "Fresh"], variation: "box 25 sachet", price: 124021 },
  { name: ["Apel Fuji", "Segar", "Fresh"], variation: "Ukuran Large", price: 56857 },
  { name: ["Wortel Berastagi"], variation: "1 paket", price: 63932 },
  { name: ["Paket Sayur Sop"], variation: "pack 250 gr", price: 42286 },
  { name: ["Apel Fuji"], variation: "per buah (~2kg)", price: 85638 },
  { name: ["Selada ORGANIK", "Fresh", "Tanpa Gula"], variation: "500 gr", price: 127866 },
  { name: ["Pisang Cavendish", "Impor"], variation: "pack 250 gr", price: 136195 },
  { name: ["Jus Jambu Merah", "Tanpa Gula"], variation: "500 gr", price: 15449 },
  { name: ["Teh Hijau", "Manis"], variation: "per sisir", price: 70632 },
  { name: ["Mangga Harum Manis"], variation: "per ikat", price: 10438 },
  { name: ["Reusable Bag", "Fresh", "ORGANIK"], variation: "per buah (~2kg)", price: 128338 },
  { name: ["Jus Jambu Merah", "Tanpa Gula", "Fresh"], variation: "per buah (~2kg)", price: 119264 },
  { name: ["Paket Sayur Sop", "ECO"], variation: "pack 200 gr", price: 96215 },
  { name: ["Wortel Berastagi", "Manis"], variation: "Ukuran Large", price: 32420 },
  { name: ["Madu Hutan Murni"], variation: "porsi besar", price: 112910 },
];